config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
root "pins#index"
get "about" => "pages#about"
get "signup" => "pages#signup"
get "login" => "pages#login"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	     validates :image, presence: true
  		 validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about 
  end
  def signup 
  end  
  def login 
  end  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 50)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)




    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_formslogin.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  
  <div class="checkbox">
  
  </div>
  <button type="submit" class="btn btn-success">Submit</button>
</form>

app/views/layouts/_formssignup.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  
  <div class="checkbox">
  
  </div>
  <button type="submit" class="btn btn-success">Submit</button>
</form>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to image_tag("logo.png", :border=>0), root_path, class: "navbar-brand" %>  </div>
    

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
                  <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

</div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <%= render 'layouts/header' %>
  <title>Parto.org</title>
<%= stylesheet_link_tag "application", media: "all" %>  
<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
<%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/_home.html.erb
<div class="container">
<div class="jumbotron center" style="width: 100%;">

  <h1>Bienvenido a Parto.org!</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>
</div>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <title>
      
        StartUp &middot; 
      
    </title>

    
      <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic|Work+Sans:300,400,500,600' rel='stylesheet' type='text/css'>
      <link href="../toolkit-startup.css" rel="stylesheet">
      <link href="../application-startup.css" rel="stylesheet">

    

    <style>
      /* note: this is a hack for ios iframe for bootstrap themes shopify page */
      /* this chunk of css is not part of the toolkit :) */
      /* …curses ios, etc… */
      @media (max-width: 768px) and (-webkit-min-device-pixel-ratio: 2) {
        body {
          width: 1px;
          min-width: 100%;
          *width: 100%;
        }
        #stage {
          height: 1px;
          overflow: auto;
          min-height: 100vh;
          -webkit-overflow-scrolling: touch;
        }
      }
    </style>
  </head>


<body>
  



<div class="stage-shelf stage-shelf-right hidden" id="sidebar">
  <ul class="nav nav-bordered nav-stacked">
    <li class="nav-header">Examples</li>
    <li class="active">
      <a href="index.html">Startup</a>
    </li>
    <li>
      <a href="minimal/index.html">Minimal</a>
    </li>
    <li>
      <a href="bold/index.html">Bold</a>
    </li>
    <li class="nav-divider"></li>
    <li class="nav-header">Docs</li>
    <li>
      <a href="docs/index.html">Toolkit</a>
    </li>
    <li>
      <a href="http://getbootstrap.com">Bootstrap</a>
    </li>
  </ul>
</div>

<div class="stage" id="stage">

<div class="block block-inverse block-fill-height app-header"
     style="background-image: url(assets/img/startup-1.jpg);">


  <nav class="navbar navbar-transparent navbar-fixed-top navbar-padded app-navbar p-t-md">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed p-x-0"
              data-target="#stage" data-toggle="stage" data-distance="-250">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">
        <strong style="background: #fff; padding: 12px; border-radius: 4px; color: #28669F;">
          go
        </strong>
      </a>
    </div>
    <div class="navbar-collapse collapse text-uppercase">
      <ul class="nav navbar-nav navbar-right">
        <li >
          <a href="/index.html">StartUp</a>
        </li>
        <li >
          <a href="minimal/index.html">Minimal</a>
        </li>
        <li >
          <a href="bold/index.html">Bold</a>
        </li>
        <li >
          <a href="docs/index.html">Docs</a>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>


  <img class="app-graph" src="assets/img/startup-0.svg">

  <div class="block-xs-middle p-b-lg">
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-md-6">
          <h1 class="block-title m-b-sm">Analytics on demand.</h1>
          <p class="lead m-b-md text-muted">Stop installing bloated scripts that all track the exact same things. Install one that does everything.</p>
          <button class="btn btn-primary btn-lg">Try it now</button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="block block-secondary app-iphone-block">
  <div class="container">
    <div class="row app-align-center">

      <div class="col-sm-5 hidden-xs">
        <img class="app-iphone" <%= image_tag "startup-2.jpg" %> style="width: 100%;">
      </div>

      

      <div class="col-sm-6 col-sm-offset-1">
        <h6 class="text-muted text-uppercase">Rich Information</h6>
        <h3 class="m-t-0">Make informed decisions with historical & real time data.</h3>
        <p class="lead m-b-md">We combine immediate real time events with rich historical data to help answer the toughest questions about retention, growth, and engagement.</p>
        <div class="row hidden-sm">
          <div class="col-sm-6 m-b-md">
            <h5 class="m-y-0">Data frequency</h5>
            <p>We poll for data on a millisecond basis. You can react to new information in seconds rather than days. <a href="#" class="text-primary">Learn more.</a></p>
          </div>
          <div class="col-sm-6">
            <h5 class="m-y-0">Reliability & uptime</h5>
            <p>We process our data across a massively distributed network of reliable servers to ensure 99.99% uptime, always. <a href="#" class="text-primary">Learn more</a>.</p>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="block block-inverse block-secondary app-code-block">
  <div class="container">
    <div class="row app-align-center">
      <div class="col-sm-5 col-sm-push-7">
        <pre class="app-code">
<span>1</span> <span class="hidden-xs">goAnalytics</span> “who are the latest 3 users?”
<span>2</span>
<span>3</span>  {
<span>4</span>    "Dave": {
<span>5</span>      "fullName": "Dave Gamache",
<span>6</span>      "twitterHandle": "@dhg",
<span>7</span>    }
<span>8</span>    "Mark": {
<span>9</span>      "fullName": "Mark Otto",
<span>10</span>      "twitterHandle": "@mdo",
<span>11</span>    }
<span>12</span>    "Jacob": {
<span>13</span>      "fullName": "Jacob Thornton",
<span>14</span>      "twitterHandle": "@fat",
<span>15</span>    }
<span>16</span>  }</pre>
      </div>

      <div class="col-sm-6 col-sm-pull-5">
        <h6 class="text-muted text-uppercase">Easy development</h6>
        <h3 class="m-t-0">Natural language queries make mining data easy for anyone.</h3>
        <p class="lead m-b-md text-muted">Rather than force everyone at your company to learn incredibly difficult terminal commands, we allow anyone to query the data with natural language to return data.</p>
        <button class="btn btn-default btn-lg btn-borderless">
          Read our docs
        </button>
      </div>
    </div>
  </div>
</div>

<div class="block block-secondary app-high-praise p-b-0">
  <div class="container">
    <div class="row app-align-center">
      <div class="col-sm-5 col-sm-push-7">
        <h6 class="text-muted text-uppercase">High Praise</h6>
        <h3 class="m-t-0 m-b-md">“Go Analytics is amazing. Decisions that used to take weeks, now only takes minutes and is available to everyone on my team.”</h3>
        <p class="m-b-md text-muted">Cindy Smith, founder of Cool Startup</p>
      </div>
      <div class="col-sm-6 col-sm-pull-5">
        <%= image_tag "startup-3.jpg" %>


      </div>
    </div>
  </div>
</div>

<div class="block app-ribbon p-y-lg">
  <div class="container text-center">
    <img src="assets/img/startup-4.svg">
    <img src="assets/img/startup-5.svg">
    <img src="assets/img/startup-6.svg">
    <img src="assets/img/startup-7.svg">
    <img src="assets/img/startup-8.svg">
  </div>
</div>

<div class="block block-secondary app-block-marketing-grid">
  <div class="container text-center">

    <div class="row m-b-lg">
      <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
        <h6 class="text-muted text-uppercase">Inside the machine</h6>
        <h3  class="m-t-0 m-b">It’s not hard to see how we make your life easier every day.</h3>
      </div>
    </div>

    <div class="row app-marketing-grid">
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/img/startup-9.svg">
        <p><strong>24/7 support.</strong> We’re always here for you no matter what time of day.</p>
      </div>
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/img/startup-10.svg">
        <p><strong>E-commerce.</strong> We automatically handle all sales analytics.</p>
      </div>
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/img/startup-11.svg">
        <p><strong>Turnaround.</strong> Our data analysis is distributed, so it processes in seconds.</p>
      </div>
    </div>

    <div class="row app-marketing-grid">
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/img/startup-12.svg">
        <p><strong>Rich calculations.</strong> Limitless ways to splice and dice your data.</p>
      </div>
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/img/startup-13.svg">
        <p><strong>Mobile apps.</strong> iOS and Android apps available for monitoring.</p>
      </div>
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/img/startup-14.svg">
        <p><strong>Secure connections.</strong> Every single request is routed through HTTPS.</p>
      </div>
    </div>
  </div>
</div>

<div class="block app-price-plans">
  <div class="container text-center">

    <div class="row m-b-lg">
      <div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
        <h6 class="text-muted text-uppercase">Business Talk</h6>
        <h3  class="m-t-0">No plans. We just bump your plan whenever you need it.</h3>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4 p-x m-b-lg">
        <div class="p-x">
          <h6 class="text-muted text-uppercase m-b">Personal</h6>
          <img class="m-b" src="assets/img/startup-15.svg">
          <p>Plenty of processing power for any personal projects, big or small.</p>
        </div>

        <ul class="list-unstyled list-bordered text-left m-y-md">
          <li class="p-y"><strong>10k</strong> monthly requests</li>
          <li class="p-y"><strong>9am-5pm</strong> technical supprt</li>
          <li class="p-y"><strong>Public</strong> API access</li>
        </ul>

        <button class="btn btn-lg btn-primary btn-block">
          Start <span class="visible-lg-inline">a personal account</span>
        </button>
      </div>

      <div class="col-sm-4 p-x m-b-lg">
        <div class="p-x">
          <h6 class="text-muted text-uppercase m-b">Business</h6>
          <img class="m-b" src="assets/img/startup-16.svg">
          <p>The perfect sized plan for small businesses to get started.</p>
        </div>

        <ul class="list-unstyled list-bordered text-left m-y-md">
          <li class="p-y"><strong>100k</strong> monthly requests</li>
          <li class="p-y"><strong>24/7</strong> technical supprt</li>
          <li class="p-y"><strong>Public</strong> API access</li>
        </ul>

        <button class="btn btn-lg btn-primary btn-block">
          Start <span class="visible-lg-inline">a business account</span>
        </button>
      </div>

      <div class="col-sm-4 p-x m-b-lg">
        <div class="p-x">
          <h6 class="text-muted text-uppercase m-b">Corporate</h6>
          <img class="m-b" src="assets/img/startup-17.svg">
          <p>An unlimited plan that will scale infinitely to any size project.</p>
        </div>

        <ul class="list-unstyled list-bordered text-left m-y-md">
          <li class="p-y"><strong>Unlimited</strong> monthly requests</li>
          <li class="p-y"><strong>24/7</strong> technical supprt</li>
          <li class="p-y"><strong>Public & Private</strong> API access</li>
        </ul>

        <button class="btn btn-lg btn-primary btn-block">
          Start <span class="visible-lg-inline">a corporate account</span>
        </button>
      </div>
    </div>

  </div>
</div>

<div class="block block-inverse app-footer">
 <div class="container">
    <div class="row">
      <div class="col-sm-5 m-b-md">
        <ul class="list-unstyled list-spaced">
          <li class="m-b"><h6 class="text-uppercase">About</h6></li>
          <li class="text-muted">
           We’ve been working on Go Analytics for the better part of a decade and are super proud of what we’ve created. If you’d like to learn more, or are interested in a job, contact us anytime at <a href="mailto: themes@getbootstrap.com">themes@getbootstrap.com</a>.
          </li>
        </ul>
      </div>
      <div class="col-sm-2 col-sm-offset-1 m-b-md">
        <ul class="list-unstyled list-spaced">
          <li class="m-b"><h6 class="text-uppercase">Product</h6></li>
          <li class="text-muted">Features</li>
          <li class="text-muted">Examples</li>
          <li class="text-muted">Tour</li>
          <li class="text-muted">Gallery</li>
        </ul>
      </div>
      <div class="col-sm-2 m-b-md">
        <ul class="list-unstyled list-spaced">
          <li class="m-b"><h6 class="text-uppercase">Apis</h6></li>
          <li class="text-muted">Rich data</li>
          <li class="text-muted">Simple data</li>
          <li class="text-muted">Real time</li>
          <li class="text-muted">Social</li>
        </ul>
      </div>
      <div class="col-sm-2 m-b-md">
        <ul class="list-unstyled list-spaced">
          <li class="m-b"><h6 class="text-uppercase">Legal</h6></li>
          <li class="text-muted">Terms</li>
          <li class="text-muted">Legal</li>
          <li class="text-muted">Privacy</li>
          <li class="text-muted">License</li>
        </ul>
      </div>
    </div>
  </div>
</div>

</div>


    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/toolkit.js"></script>
    <script src="assets/js/application.js"></script>
  </body>
</html>

app/views/pages/login.html.erb
<div class = "container">

<div class="jumbotron center">
     <h1>Welcome to my appa!</h1>
     <p>
     	<%= render 'layouts/formssignup' %>
       
  </p>    
</div>

app/views/pages/signup.html.erb
<div class = "container">

<div class="jumbotron center">
     <h1>Welcome to my appa!</h1>
     <p>
     	<%= render 'layouts/formssignup' %>
       
  </p>    
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
<div/>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>


<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
    <div class="panel-heading"><strong>Clase de evento</strong></div>

    <%= link_to image_tag(pin.image.url(:medium)), pin%>
      <div class="panel-body">
        <%= pin.description %>
        <p><strong><%= pin.user.name if pin.user %></strong></p>
        <%= link_to 'Show', pin_path(pin) %>
        <% if pin.user == current_user %>
              <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="container">
<div class="jumbotron">
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>
</div>
</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
    <div class="panel-heading"><strong>Clase de evento</strong></div>
  </div>
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
        </div>
    
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>




        <% if @pin.user == current_user %>
              <%= link_to edit_pin_path(@pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>        
            <% end %>

      </div>
    </div>
  </div>
</div>